# Generated by Django 5.0.3 on 2024-03-23 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='posted',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
