# Generated by Django 5.0.3 on 2024-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='car_fuel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rent',
            name='car_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rent',
            name='car_seater',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
