# Generated by Django 5.0.3 on 2024-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_rent_car_fuel_rent_car_name_rent_car_seater_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
