# Generated by Django 5.0.3 on 2024-03-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_rename_cars_rent_fromdate_rename_date_rent_todate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='car_id',
        ),
    ]
