# Generated by Django 5.0.3 on 2024-03-29 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_rent_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='fromdate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rent',
            name='todate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
