# Generated by Django 5.0.3 on 2024-03-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0024_alter_car_car_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
