# Generated by Django 5.0.3 on 2024-03-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0027_alter_car_car_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent',
            new_name='Order',
        ),
    ]
