# Generated by Django 5.0.3 on 2024-03-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0028_rename_rent_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Rent',
        ),
    ]
