# Generated by Django 5.0.3 on 2024-03-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0029_rename_order_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.TextField(default=0, primary_key=True, serialize=False),
        ),
    ]
