# Generated by Django 5.0.3 on 2024-03-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0033_alter_car_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
