# Generated by Django 5.0.3 on 2024-03-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0036_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='order_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
