# Generated by Django 5.0.3 on 2024-03-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0038_alter_rent_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='rent',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
