# Generated by Django 5.0.3 on 2024-03-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0039_delete_order_alter_rent_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
