# Generated by Django 5.0.3 on 2024-03-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0041_remove_rent_name_rent_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='fullname',
            new_name='name',
        ),
    ]
