# Generated by Django 5.0.3 on 2024-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0042_rename_fullname_rent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
