# Generated by Django 5.0.3 on 2024-03-30 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0043_rent_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardholder',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='expdate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
