# Generated by Django 5.0.3 on 2024-03-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0044_payment_amount_payment_cardholder_payment_cardno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
