# Generated by Django 5.0.3 on 2024-03-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0045_alter_car_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='order_id',
            new_name='id',
        ),
    ]
