# Generated by Django 5.0.3 on 2024-03-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0046_rename_order_id_rent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='id',
            new_name='oid',
        ),
    ]
