# Generated by Django 5.0.3 on 2024-03-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0047_rename_id_rent_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='userid',
        ),
    ]
