# Generated by Django 5.0.3 on 2024-03-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0048_remove_rent_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
