# Generated by Django 5.0.3 on 2024-03-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0049_alter_car_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='name',
            new_name='Fullname',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='username',
        ),
    ]
