# Generated by Django 5.0.3 on 2024-03-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0050_rename_name_rent_fullname_remove_payment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='Fullname',
            new_name='name',
        ),
    ]
